### PR TITLE
Avoid duplicate gui problem that can corrupt saves

### PR DESCRIPTION
**Pull request by gmt**
Signed-off-by: Gregory M. Turner gmt@be-evil.net

### CODE REVIEW

**Comment by GopherAtl** [comment]
thankee-sai.

**Comment by gmt** [comment]
yw... but fyi please see my post to the autowire mod thread; (summary: as things stand after this merge, one of us -- likely me -- has spawned a minor bug).

**Comment by GopherAtl** [comment]
I saw, but as I said on the forum, the new bug seems highly preferable to the old bug, since the new bug is a minor nuisance that may cost a few wires, while the previous bug was potentially save-corrupting.

**Comment by gmt** [comment]
Ah, ACK, didn't notice

**Comment by GopherAtl** [comment]
I commented here first, probably hadn't posted yet at the time you commented

**Pull request merged**
